### ISSUE TITLE
Add rest of API?

### ISSUE THREAD

**Issue by stormlifter** [dnsimple/dnsimple-python#1]
Any chance of adding the other portions of the API? Like the ability to add services and other API functions?

**Comment by onlyhavecans** [comment]
I would like to get the rest added, but I have very little time to work on this lately.

There is no 'official' DNSimple binding. This is just one of a few. I would like this to be an official library but it will require a lot of work to get it to standards

**Comment by onlyhavecans** [comment]
This is now covered in 2.0.0
