### ISSUE TITLE
list_contacts returns a list of the same contact instead of a list of all contacts

### ISSUE THREAD

**Issue by colbyprior** [dnsimple/dnsimple-python#252]
Hi All,

When calling `list_contacts` function from the `contacts` service returns a list of all of the same contacts.

For example (I changed my contact id to 12345 for the example):
```
>>> contact_list = client.contacts.list_contacts(account_id)
>>> for contact in contact_list.data:
...     print(contact.id)
...
12345
12345
12345
>>>
```
The `contact` struct gets overwritten when it is created.

https://github.com/dnsimple/dnsimple-python/compare/main...colbyprior:main
Running the code above with this fix I then get three different contact id's as is intended.

**Comment by ecomba** [comment]
Thank you so much for submitting this Colby!

I'll check it today!
