### ISSUE TITLE
Implement DNSimple's HTTP fixtures instead of using sandbox

### ISSUE THREAD

**Issue by onlyhavecans** [dnsimple/dnsimple-python#31]
DNSimple uses HTTP fixtures for all their tests on official clients. I would like to switch to them. I do not know how to implement this in python with `requests` and `pytest` though. Googling about is not super useful either

See https://blog.dnsimple.com/2017/01/api-client-testing-with-http-fixtures/
See https://github.com/dnsimple/dnsimple-developer/tree/master/fixtures/v2

**Comment by weppos** [comment]
I found https://pypi.python.org/pypi/requests-mock that seems very close to what we do in other clients, such as the Ruby one.
https://github.com/dnsimple/dnsimple-ruby/blob/master/spec/dnsimple/client/certificates_spec.rb#L11-L14

It may be worth investigating.

**Comment by onlyhavecans** [comment]
I finally found exactly what I am looking for https://github.com/tonybaloney/requests-staticmock

**Comment by weppos** [comment]
That definitely looks very similar to what we do in other clients 👍

**Comment by onlyhavecans** [comment]
This is now covered in 2.0.0
