### ISSUE TITLE
TypeError: option values must be strings

### ISSUE THREAD

**Issue by TonyStew** [dnsimple/dnsimple-python#43]
Using the .dnsimple file authentication option results in a `TypeError: option values must be strings` error.

I believe this occurs do to a change in ConfigParser for Python3.7.  I fixed it by setting `allow_no_value=True` in the ConfigParser call on line 104 of dnsimple.py.

**Comment by onlyhavecans** [comment]
Thanks for reporting this. I will look into patching this soon

**Comment by marco-giovannini-clevertech** [comment]
I get a similar issue but on line 145 fail to render the error message.
raise DNSimpleException('Account {} not found. Possible variants: {}'.format(self._account_id, ', '.join(ids)))

  File "/usr/local/lib/python3.6/dist-packages/dnsimple/dnsimple.py", line 145, in account_id
    ', '.join(ids)))
TypeError: sequence item 0: expected str instance, int found

But even if I remove the part to be rendered fail throwing the exception "Account not found|"  but my account exists.

This is how I have instantiated the client.

dns_client = DNSimple(api_token=''xxxxxx, account_id='xxxx')

Python 3.6.9

I am still investigating it.

**Comment by usernkey** [comment]
I get a similar issue but on line 145 fail to render the error message. raise DNSimpleException('Account {} not found. Possible variants: {}'.format(self._account_id, ', '.join(ids)))
File "/usr/local/lib/python3.6/dist-packages/dnsimple/dnsimple.py", line 145, in account_id ', '.join(ids))) TypeError: sequence item 0: expected str instance, int found
But even if I remove the part to be rendered fail throwing the exception "Account not found|" but my account exists.
This is how I have instantiated the client.
dns_client = DNSimple(api_token=''xxxxxx, account_id='xxxx')
Python 3.6.9
I am still investigating it.

**Comment by usernkey** [comment]
I found the problem. I will open a separate issue and PR.

**Comment by weppos** [comment]
Hey Marco, thanks for the help!

FYI we are currently working on a completely redesigned API client. The "master" branch is already hosting that code, you can find the old code in the "v1" branch.

We have not released it to Pypi yet as we are finalizing the review. Would you be interested to try our new version? There's a good chance it won't have this issue.

**Comment by usernkey** [comment]
Yes, I can give it try.

**Comment by onlyhavecans** [comment]
This form of authentication is no longer supplied inside of the client in 2.x. If you wish to load your authentication from a file you will want to handle the file read and parse in your own code.
