### ISSUE TITLE
TypeError: sequence item 0: expected str instance, int found

### ISSUE THREAD

**Issue by usernkey** [dnsimple/dnsimple-python#56]
On line 145 fail to render the error message. raise DNSimpleException('Account {} not found. Possible variants: {}'.format(self._account_id, ', '.join(ids)))
File "/usr/local/lib/python3.6/dist-packages/dnsimple/dnsimple.py", line 145, in account_id ', '.join(ids))) TypeError: sequence item 0: expected str instance, int found
But even if I remove the part to be rendered fail throwing the exception "Account not found|" but my account exists.
This is how I have instantiated the client.
dns_client = DNSimple(api_token=''xxxxxx, account_id='xxxx')
Python 3.6.9

**Comment by usernkey** [comment]
In the dnsimple.py file in the function account_id

The el['id'] element must be converted to strings.

ids = [str(el['id']) for el in data]

**Comment by DXTimer** [comment]
@usernkey as v1 of the python client wasn't an official client release we are not extending maintenance and support to the v1 client version. I would recommend migrating to the latest v2 client version, to ensure continued support, and make use of new features. You can find more about the DNSimple API v2 at our developer site [https://developer.dnsimple.com/](https://developer.dnsimple.com/).
